export class CollectDeposit {

    static collectDepositJson(obj: CollectDeposit) {
        return new CollectDeposit(
            obj['co_client'],
            obj['co_collection'],
            obj['co_currency'],
            obj['co_document'],
            obj['co_enterprise'],
            obj['co_original_collection'],
            obj['co_type'],
            obj['coordenada'],
            obj['da_collection'],
            obj['da_rate'],
            obj['hasIGTF'],
            obj['id_client'],
            obj['id_collection'],
            obj['id_currency'],
            obj['id_enterprise'],
            obj['lb_client'],
            obj['na_responsible'],
            obj['nu_amount_final'],
            obj['nu_amount_final_conversion'],
            obj['nu_amount_igtf'],
            obj['nu_amount_igtf_conversion'],
            obj['nu_amount_total'],
            obj['nu_amount_total_conversion'],
            obj['nu_difference'],
            obj['nu_difference_conversion'],
            obj['nu_igtf'],
            obj['nu_value_local'],
            obj['st_collection'],
            obj['total_deposit'],
            obj['tx_comment'],
            obj['tx_conversion'],
            obj['isSelected'],
            obj['inDepositCollect'],
        );
    }
    constructor(
        public co_client: string = "",
        public co_collection: string = "",
        public co_currency: string = "",
        public co_document: string = "",
        public co_enterprise: string = "",
        public co_original_collection: string = "",
        public co_type: number = 0,
        public coordenada: string = "",
        public da_collection: string = "",
        public da_rate: string = "",
        public hasIGTF: string = "",
        public id_client: number = 0,
        public id_collection: number = 0,
        public id_currency: number = 0,
        public id_enterprise: number = 0,
        public lb_client: string = "",
        public na_responsible: "",
        public nu_amount_final: number = 0,
        public nu_amount_final_conversion: number = 0,
        public nu_amount_igtf: number = 0,
        public nu_amount_igtf_conversion: number = 0,
        public nu_amount_total: number = 0,
        public nu_amount_total_conversion: number = 0,
        public nu_difference: number = 0,
        public nu_difference_conversion: number = 0,
        public nu_igtf: number = 0,
        public nu_value_local: number = 0,
        public st_collection: number = 0,
        public total_deposit: number = 0,
        public tx_comment: string = "",
        public tx_conversion: string = "",
        public isSelected: boolean = false,
        public inDepositCollect: boolean = false,
    ) { }
}
