DROP TABLE IF EXISTS public.application_tags;

CREATE TABLE IF NOT EXISTS public.application_tags
(
    id_application_tag serial not null,
    co_application_tag text,
	co_language text COLLATE pg_catalog."default",
	co_module text COLLATE pg_catalog."default",
    na_module text COLLATE pg_catalog."default",	
    tag text COLLATE pg_catalog."default",    
    co_operation character(1) COLLATE pg_catalog."default",
	da_update timestamp without time zone,    
    CONSTRAINT pk_application_tags PRIMARY KEY (id_application_tag),
	UNIQUE (co_application_tag, co_language)
)

TABLESPACE pg_default;

ALTER TABLE public.application_tags
    OWNER to postgres;

-- Trigger: application_tags

-- DROP TRIGGER application_tags_da_update ON public.application_tags;

CREATE TRIGGER application_tags_da_update
    BEFORE INSERT OR UPDATE 
    ON public.application_tags
    FOR EACH ROW
    EXECUTE FUNCTION public.da_update();

-- INDEX
CREATE INDEX IF NOT EXISTS application_tags_co_module_idx ON public.application_tags USING btree (co_module);	

--PEDIDOS
DELETE FROM public.application_tags WHERE co_module = 'PED';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('PED_NOMBRE_MODULO', 'PED', 'PEDIDOS', 'ESP', 'Pedidos'),
	('PED_NUEVO_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'PEDIDO'),
	('PED_BUSCAR_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'BUSCAR'),
	('PED_COPIAR_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'COPIAR'),
	('PED_NOMBRE_MODULO', 'PED', 'PEDIDOS', 'ENG', 'Orders'),
	('PED_NUEVO_PEDIDO', 'PED', 'PEDIDOS', 'ENG', 'New Order'),
	('PED_BUSCAR_PEDIDO', 'PED', 'PEDIDOS', 'ENG', 'Find Order'),
	('PED_COPIAR_PEDIDO', 'PED', 'PEDIDOS', 'ENG', 'Copy Orders'),
	('PED_STATUS_TO_SEND', 'PED', 'PEDIDOS', 'ESP', 'Por Enviar'),
	('PED_STATUS_SENT', 'PED', 'PEDIDOS', 'ESP', 'Enviado'),
	('PED_STATUS_SAVED', 'PED', 'PEDIDOS', 'ESP', 'Guardado'),
	('PED_TAB_GENERAL', 'PED', 'PEDIDOS', 'ESP', 'General'),
	('PED_TAB_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'Pedido'),
	('PED_TAB_TOTAL', 'PED', 'PEDIDOS', 'ESP', 'Total'),
	('PED_TAB_ADJUNTO', 'PED', 'PEDIDOS', 'ESP', 'Adjunto'),
	('PED_NU_REF', 'PED', 'PEDIDOS', 'ESP', 'Nro. Ref.'),
	('PED_CLIENTE', 'PED', 'PEDIDOS', 'ESP', 'Cliente'),
	('PED_STATUS', 'PED', 'PEDIDOS', 'ESP', 'Estatus'),
	('PED_FECHA', 'PED', 'PEDIDOS', 'ESP', 'Fecha'),
	('PED_EMPRESA', 'PED', 'PEDIDOS', 'ESP', 'Empresa'),
	('PED_MONEDA', 'PED', 'PEDIDOS', 'ESP', 'Moneda'),
	('PED_TASA_CAMBIO', 'PED', 'PEDIDOS', 'ESP', 'Tasa de Cambio'),
	('PED_SUCURSAL', 'PED', 'PEDIDOS', 'ESP', 'Sucursal'),
	('PED_TIPO_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'Tipo Pedido'),
	('PED_LISTA_PRECIO', 'PED', 'PEDIDOS', 'ESP', 'Lista de Precio'),
	('PED_NUMERO_ORDEN', 'PED', 'PEDIDOS', 'ESP', 'Numero de Orden'),
	('PED_DA_ORDER', 'PED', 'PEDIDOS', 'ESP', 'Fecha Pedido'),
	('PED_DA_DISPATCH', 'PED', 'PEDIDOS', 'ESP', 'Fecha Despacho'),
	('PED_RESPONSABLE', 'PED', 'PEDIDOS', 'ESP', 'Responsable'),
	('PED_COMENTARIO', 'PED', 'PEDIDOS', 'ESP', 'Comentario'),
	('PED_CONDICION_PAGO', 'PED', 'PEDIDOS', 'ESP', 'Condicion de pago'),
	('PED_X_APROBAR', 'PED', 'PEDIDOS', 'ESP', 'Por Aprobar'),
	('PED_LIMITE_CREDITO', 'PED', 'PEDIDOS', 'ESP', 'Límite de Credito'),
	('PED_TOTAL_ITEMS', 'PED', 'PEDIDOS', 'ESP', 'Total Items'),
	('PED_TOTAL_UNIDAD', 'PED', 'PEDIDOS', 'ESP', 'Total por unidad'),
	('PED_TOTAL_BASE', 'PED', 'PEDIDOS', 'ESP', 'Total Base'),
	('PED_TOTAL_PEDIDO', 'PED', 'PEDIDOS', 'ESP', 'Total Pedido'),
	('PED_TOTAL_IVA', 'PED', 'PEDIDOS', 'ESP', 'Total IVA'),
	('PED_TASA', 'PED', 'PEDIDOS', 'ESP', 'Tasa'),
	('PED_LINEA', 'PED', 'PEDIDOS', 'ESP', 'Línea'),
	('PED_CODIGO', 'PED', 'PEDIDOS', 'ESP', 'Código'),
	('PED_ALMACEN', 'PED', 'PEDIDOS', 'ESP', 'Almacén'),
	('PED_PRECIO_LISTA', 'PED', 'PEDIDOS', 'ESP', 'Precio Lista'),
	('PED_RIF', 'PED', 'PEDIDOS', 'ESP', 'RIF'),
	('PED_CONTACTO', 'PED', 'PEDIDOS', 'ESP', 'Contacto'),
	('PED_EMAIL', 'PED', 'PEDIDOS', 'ESP', 'E-Mail'),
	('PED_TELEFONO', 'PED', 'PEDIDOS', 'ESP', 'Teléfono'),
	('PED_SALDO', 'PED', 'PEDIDOS', 'ESP', 'Saldo'),
	('PED_CREDITO', 'PED', 'PEDIDOS', 'ESP', 'Crédito'),
	('PED_DIRECCION', 'PED', 'PEDIDOS', 'ESP', 'Dirección'),
	('PED_BUSQUEDA', 'PED', 'PEDIDOS', 'ESP', 'Pedidos...'),
	('PED_MINIMO', 'PED', 'PEDIDOS', 'ESP', 'Mínimo'),
	('PED_MULTIPLO', 'PED', 'PEDIDOS', 'ESP', 'Múltiplo'),
	('PED_CANTIDAD', 'PED', 'PEDIDOS', 'ESP', 'Cantidad'),
	('PED_IVA', 'PED', 'PEDIDOS', 'ESP', 'IVA'),
	('PED_DC', 'PED', 'PEDIDOS', 'ESP', 'Descuento'),
	('PED_UNIDAD', 'PED', 'PEDIDOS', 'ESP', 'Unidad'),
	('PED_FAVORITO', 'PED', 'PEDIDOS', 'ESP', 'Favoritos'),
	('PED_PLACEHOLDER_CANTIDAD', 'PED', 'PEDIDOS', 'ESP', 'Ingrese Cantidad'),
	('PED_PLACEHOLDER_PRICELIST', 'PED', 'PEDIDOS', 'ESP', 'Seleccione Lista Precio'),
	('PED_PLACEHOLDER_UNIDAD', 'PED', 'PEDIDOS', 'ESP', 'Seleccione Unidad'),
	('PED_PLACEHOLDER_IVA', 'PED', 'PEDIDOS', 'ESP', 'Seleccione IVA'),
	('PED_PLACEHOLDER_DESCUENTO', 'PED', 'PEDIDOS', 'ESP', 'Seleccione Descuento'),
	('PED_PLACEHOLDER_ALMACEN', 'PED', 'PEDIDOS', 'ESP', 'Seleccione Almacén'),
	('PED_PLACEHOLDER_CLIENTE', 'PED', 'PEDIDOS', 'ESP', 'Seleccione Cliente'),
	('PED_INFO_CLIENTE', 'PED', 'PEDIDOS', 'ESP', 'Información de Cliente'),
	('PED_CANAL_DISTRIBUCION', 'PED', 'PEDIDOS', 'ESP', 'Canal de Distribución'),
	('PED_GLOBAL_DC', 'PED', 'PEDIDOS', 'ESP', 'Descuento Global'),
	('PED_PRODUCT_DC', 'PED', 'PEDIDOS', 'ESP', 'Descuento productos'),
	('PED_MINUS_DC', 'PED', 'PEDIDOS', 'ESP', 'Monto - Desc.'),
	('PED_PLUS_IVA', 'PED', 'PEDIDOS', 'ESP', 'Monto + IVA'),
	('PED_NO_DC', 'PED', 'PEDIDOS', 'ESP', 'SIN DESCUENTO'),
	('PED_ELIMINAR_PEDIDO', 'PED', 'PEDIDOS', 'ESP', '¿Seguro que quieres eliminar este pedido?'),
	('PED_ERROR_INVENTARIO', 'PED', 'PEDIDOS', 'ESP', 'Debe ingresar un valor menor o igual al inventario.'),
	('PED_ERROR_STOCK0', 'PED', 'PEDIDOS', 'ESP', 'No se puede agregar productos sin inventario'),
	('PED_CHECK_CLIENTE', 'PED', 'PEDIDOS', 'ESP', 'El campo de cliente no puede estar vacio'),
	('PED_AVISO_GUARDADO', 'PED', 'PEDIDOS', 'ESP', 'Pedido Guardado'),
	('PED_AVISO_COPIADO', 'PED', 'PEDIDOS', 'ESP', 'Pedido Copiado Exitosamente'),
	('PED_PREGUNTA_GUARDADO', 'PED', 'PEDIDOS', 'ESP', '¿Desea Enviar el pedido?'),
	('PED_ERROR_SUGERIR','PED','PEDIDOS','ESP','No se pudieron cargar ciertos productos al pedido. Verifique antes de enviar.'),
	('PED_RESET_PRICELIST', 'PED', 'PEDIDOS', 'ESP', 'El pedido ya tiene productos con la lista de precio anterior, para cambiar la lista de precio se debe reiniciar el pedido'),
	('PED_RESET_MONEDA', 'PED', 'PEDIDOS', 'ESP', 'El pedido ya tiene productos con la moneda anterior, para cambiar la moneda se debe reiniciar el pedido'),
	('PED_ERROR_PRICELIST', 'PED', 'PEDIDOS', 'ESP', 'No tiene lista de precio asociada para esta moneda'),
	('PED_RESET_ORDERTYPE', 'PED', 'PEDIDOS', 'ESP', '¿Seguro desea cambiar el Tipo de Pedido? ¡El pedido sera reiniciado!'),
	('PED_RESET_EMPRESA', 'PED', 'PEDIDOS', 'ESP', 'El pedido tiene elementos de otra empresa, para continuar se debe reiniciar el pedido. ¿Desea reiniciar el pedido?'),
	('PED_AVISO_PMM1', 'PED', 'PEDIDOS', 'ESP', 'La Cantidad Minima de este Producto es '),
	('PED_AVISO_PMM2', 'PED', 'PEDIDOS', 'ESP', ' y el multiplo es '),
	('PED_PLACEHOLDER_DCTO', 'PED', 'PEDIDOS', 'ESP', '% Descuento'),
	('PED_DESDE', 'PED', 'PEDIDOS', 'ESP', ' desde '),
	('PED_BORRAR', 'PED', 'PEDIDOS', 'ESP', 'BORRAR'),
	('PED_CARRITO', 'PED', 'PEDIDOS', 'ESP', 'Carrito'),
	('PED_CERRAR', 'PED', 'PEDIDOS', 'ESP', 'CERRAR');

DELETE FROM public.application_tags WHERE co_module = 'CLI';
--TAGS CLIENTES - NUEVO CLIENTE POTENCIAL
INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('CLI_NEW_POT_NOMBRE_MODULO','CLI','CLIENTES','ESP','Clientes'),
	('CLI_NEW_POT_NOMBRE','CLI','CLIENTES','ESP','Nombre'),
	('CLI_NEW_POT_RIF','CLI','CLIENTES','ESP','Rif'),
	('CLI_NEW_POT_DIRECCION','CLI','CLIENTES','ESP','Dirección'),
	('CLI_NEW_POT_DIRECCION_ENTREGA','CLI','CLIENTES','ESP','Dirección Entrega'),
	('CLI_NEW_POT_OBSERVACION','CLI','CLIENTES','ESP','Observación'),
	('CLI_NEW_POT_RESPONSABLE','CLI','CLIENTES','ESP','Responsable'),
	('CLI_NEW_POT_EMAIL','CLI','CLIENTES','ESP','Email'),
	('CLI_NEW_POT_TELEFONO','CLI','CLIENTES','ESP','Teléfono'),
	('CLI_NEW_POT_WEB','CLI','CLIENTES','ESP','Web'),
	('CLI_NEW_BOTON_GUARDAR','CLI', 'CLIENTES','ESP','Guardar'),
	('CLI_NEW_POT_BOTON_ENVIAR','CLI', 'CLIENTES','ESP','Enviar'),
	('CLI_NEW_POT_MENSAJE_ERROR_NOMBRE_CLIENTE','CLI', 'CLIENTES','ESP','Nombre obligatorio.'),
	('CLI_SELECTOR','CLI','CLIENTES','ESP','Seleccione...'),
	('CLI_NEW_POT_EMPRESA','CLI','CLIENTES','ESP','Empresa'),
	('CLI_LOCATION','CLI','CLIENTES','ESP','Ingrese ubicación'),
	('CLI_COORDENADA','CLI','CLIENTES','ESP','Ingrese Coordenada'),
	('CLI_NOMBRE_MODULO', 'CLI', 'CLIENTES', 'ESP','Clientes'),
	('CLI_CODIGO', 'CLI', 'CLIENTES', 'ESP','Código'),
	('CLI_SALDO', 'CLI', 'CLIENTES', 'ESP','Saldo'),
	('CLI_EMPRESA', 'CLI', 'CLIENTES', 'ESP','Empresa'), 
	('CLI_POT_NOMBRE_MODULO','CLI','CLIENTES','ESP','Clientes'),
	('CLI_POT_LISTADO','CLI','CLIENTES','ESP','Listado Cliente Potencial'),
	('CLI_POT_CLIENTE','CLI','CLIENTES','ESP','Cliente'),
	('CLI_POT_RIF','CLI','CLIENTES','ESP','RIF'),
	('CLI_POT_REFERENCIA','CLI','CLIENTES','ESP','Nro. Ref'),
	('CLI_POT_TELEFONO','CLI','CLIENTES','ESP','Nro. Teléfono'),
	('CLI_POT_DIRECCION','CLI','CLIENTES','ESP','Dirección'),
	('CLI_POT_ESTATUS','CLI','CLIENTES','ESP','Estatus'),
	('CLI_POT_ID','CLI','CLIENTES','ESP','Id'),
	('CLI_POT_GUARDADO','CLI','CLIENTES','ESP','Guardado'),
	('CLI_POT_POR_ENVIAR','CLI','CLIENTES','ESP','Por Enviar'),
	('CLI_POT_ENVIADO','CLI','CLIENTES','ESP','Enviado'),
	('CLI_POT_BORRAR','CLI','CLIENTES','ESP','Borrar'),
	('CLI_DETAIL_TAB_DETALLE','CLI','CLIENTES','ESP','Detalle'),
	('CLI_DETAIL_TAB_DOCUMENTO_VENTA','CLI','CLIENTES','ESP','Doc. de Venta'),
	('CLI_DETAIL_EMPRESA','CLI','CLIENTES','ESP','Empresa'),
	('CLI_DETAIL_NOMBRE','CLI','CLIENTES','ESP','Nombre'),
	('CLI_DETAIL_CODIGO','CLI','CLIENTES','ESP','Código'),
	('CLI_DETAIL_LISTA_PRECIO','CLI','CLIENTES','ESP','Lista de Precio'),
	('CLI_DETAIL_CONTACTO','CLI','CLIENTES','ESP','Contacto'),
	('CLI_DETAIL_EMAIL','CLI','CLIENTES','ESP','Email'),
	('CLI_DETAIL_TELEFONO','CLI','CLIENTES','ESP','Teléfono'),
	('CLI_DETAIL_SALDO','CLI','CLIENTES','ESP','Saldo'),
	('CLI_DETAIL_CREDITO','CLI','CLIENTES','ESP','Crédito'),
	('CLI_DETAIL_CONDICION_PAGO','CLI','CLIENTES','ESP','Condición de Pago'),
	('CLI_DETAIL_DIRECCION','CLI','CLIENTES','ESP','Dirección'),
	('CLI_DETAIL_FECHA_DOCUMENTO','CLI','CLIENTES','ESP','Fecha Doc.'),
	('CLI_DETAIL_FECHA_VENCIMIENTO','CLI','CLIENTES','ESP','Fecha Venc.'),
	('CLI_DETAIL_DIAS_VENCIMIENTO','CLI','CLIENTES','ESP','Días Venc.'),
	('CLI_DETAIL_NUMERO_DOCUMENTO','CLI','CLIENTES','ESP','Nº Doc.'),
	('CLI_DETAIL_MONEDA_DOC','CLI','CLIENTES','ESP','Moneda Doc.'),
	('CLI_DETAIL_TIPO','CLI','CLIENTES','ESP','Tipo'),
	('CLI_DETAIL_TASA','CLI','CLIENTES','ESP','Tasa'),
	('CLI_DETAIL_MONTO','CLI','CLIENTES','ESP','Monto'),
	('CLI_DETAIL_COORDENADA','CLI','CLIENTES','ESP','Coordenada'),
	('CLI_LOCATION_ACEPTAR','CLI','CLIENTES','ESP','Aceptar'),
	('CLI_DENARIO_HEADER','CLI','CLIENTES','ESP','Denario Clientes'),
	('CLI_HOME_LIST_CLIENT','CLI','CLIENTES','ESP','CLIENTES'),
	('CLI_HOME_NEW_POTENTIAL_CLIENT','CLI','CLIENTES','ESP','CLIENTE POTENCIAL'),
	('CLI_HOME_FIND_POTENTIAL_CLIENT','CLI','CLIENTES','ESP','BUSCAR CLIENTE POTENCIAL'),
	('CLI_DENARIO_CONFIRM_SEND_LOCATION','CLI','CLIENTES','ESP','¿Desea enviar la nueva coordenada?'),
	('CLI_DENARIO_CONFIRM_SEND_POTENTIAL_CLIENT','CLI','CLIENTES','ESP','¿Desea enviar nuevo Cliente Potencial?'),
	('CLI_SEGMENT_GENERAL','CLI','CLIENTES','ESP','General'),
	('CLI_SEGMENT_ADJUNTOS','CLI','CLIENTES','ESP','Adjuntos'),
	('CLI_PLACEHOLDER','CLI','CLIENTES','ESP','Clientes...'),
	('CLI_DOC_SALE_CODOC_SALE_TYPE','CLI','CLIENTES','ESP','Tipo'),
	('CLI_DOC_SALE_CODOC','CLI','CLIENTES','ESP','Código'),
	('CLI_DOC_SALE_NUDOC','CLI','CLIENTES','ESP','Aplicar a:'),
	('CLI_DOC_SALE_DADOC','CLI','CLIENTES','ESP','Fecha Doc'),
	('CLI_DOC_SALE_DADUEDATE','CLI','CLIENTES','ESP','Fecha Venc'),
	('CLI_DOC_SALE_NUAMOUNTTOTAL','CLI','CLIENTES','ESP','Monto'),
	('CLI_DOC_SALE_NUBALANCE','CLI','CLIENTES','ESP','Saldo'),
	('CLI_DOC_SALE_TXCOMMENT','CLI','CLIENTES','ESP','Comentario'),
	('CLI_DOC_SALE_BUTTON_VIEW','CLI','CLIENTES','ESP','Ver'),
	('CLI_ACEPTAR','CLI','CLIENTES','ESP','Aceptar'),
	('CLI_CANCELAR','CLI','CLIENTES','ESP','Cancelar'),
	('CLI_SELECTOR_HEADER','CLI','CLIENTES','ESP',''),
	('CLI_HEADER_ALERTA', 'CLI', 'CLIENTES', 'ESP','¡Alerta!'),
	('CLI_RESET_CONFIRMA', 'CLI', 'CLIENTES', 'ESP','Se ha detectado cambio del cliente por lo que debera iniciar nuevamente la transacción.');
	
-- TAGS COBROS
DELETE FROM public.application_tags WHERE co_module = 'COB';
-- TAGS COBROS
INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('COB_NOMBRE_MODULO','COB','COBROS','ESP','Cobros'),
	('COB_NOMBRE_MODULO_ANTICIPO','COB','COBROS','ESP','Anticipo'),
	('COB_NOMBRE_MODULO_RETENTION','COB','COBROS','ESP','Retención'),
	('COB_NOMBRE_MODULO_IGTF','COB','COBROS','ESP','IGTF'),
	('COB_MODULE_NUEVO_COBRO','COB','COBROS','ESP','COBRO'),
	('COB_MODULE_ANTICIPO_PREPAGO','COB','COBROS','ESP','ANTICIPO/PREPAGO'),
	('COB_MODULE_RETENTION','COB','COBROS','ESP','RETENCIÓN'),
	('COB_MODULE_IGTF','COB','COBROS','ESP','IGTF'),
	('COB_MODULE_BUSCAR','COB','COBROS','ESP','BUSCAR'),
	('COB_PESTANA_GENERAL','COB','COBROS','ESP','General'),
	('COB_PESTANA_DOCUMENTOS','COB','COBROS','ESP','Documentos'),
	('COB_PESTANA_PAGOS','COB','COBROS','ESP','Pagos'),
	('COB_PESTANA_TOTAL','COB','COBROS','ESP','Total'),
	('COB_PESTANA_ADJUNTOS','COB','COBROS','ESP','Adjuntos'),
	('COB_CLIENTE','COB','COBROS','ESP','Cliente'),
	('COB_MONEDA','COB','COBROS','ESP','Moneda'),
	('COB_TASA','COB','COBROS','ESP','Tasa'),
	('COB_FECHA_TASA','COB','COBROS','ESP','Fecha Tasa'),
	('COB_FECHA_COBRO','COB','COBROS','ESP','Fecha Cobro'),
	('COB_RESPONSABLE','COB','COBROS','ESP','Responsable'),
	('COB_COMENTARIO','COB','COBROS','ESP','Comentario'),
	('COB_RAZON_CAMBIO_TASA','COB','COBROS','ESP','Razon Cambio Tasa'),
	('COB_MONTO_TOTAL','COB','COBROS','ESP','Monto total a pagar'),
	('COB_EFECTIVO','COB','COBROS','ESP','Efectivo'),
	('COB_CHEQUE','COB','COBROS','ESP','Cheque'),
	('COB_DEPOSITO','COB','COBROS','ESP','Depósito'),
	('COB_TRANSFERENCIA','COB','COBROS','ESP','Transferencia'),
	('COB_OTROS','COB','COBROS','ESP','Otros'),
	('COB_BANCO_EMISOR','COB','COBROS','ESP','Banco Emisor'),
	('COB_NUEVA_CUENTA','COB','COBROS','ESP','Nueva cuenta'),
	('COB_FECHA','COB','COBROS','ESP','Fecha'),
	('COB_ACEPTAR','COB','COBROS','ESP','Aceptar'),
	('COB_CANCELAR','COB','COBROS','ESP','Cancelar'),
	('COB_MONTO','COB','COBROS','ESP','Monto'),
	('COB_FECHA_VALOR','COB','COBROS','ESP','Fecha valor'),
	('COB_NRO_CHEQUE','COB','COBROS','ESP','Nro. Cheque'),
	('COB_NO_DOCUMENTOS','COB','COBROS','ESP','No hay documentos'),
	('COB_SELECCIONE','COB','COBROS','ESP','Seleccione'),
	('COB_TIPO','COB','COBROS','ESP','Tipo'),
	('COB_MONEDA_DOCUMENTO','COB','COBROS','ESP','Moneda documento'),
	('COB_DIAS_VENCIMIENTO','COB','COBROS','ESP','Días vencimiento'),
	('COB_SALDO','COB','COBROS','ESP','Saldo'),
	('COB_FECHA_DOC','COB','COBROS','ESP','Fecha documento'),
	('COB_FECHA_VENCIMIENTO','COB','COBROS','ESP','Fecha vencimiento'),
	('COB_DETALLE_DOCUMENTO','COB','COBROS','ESP','Detalle documento'),
	('COB_TIPO_DOCUMENTO','COB','COBROS','ESP','Tipo documento'),
	('COB_NRO_DOCUMENTO','COB','COBROS','ESP','Nro. documento'),
	('COB_FECHA_EMISION','COB','COBROS','ESP','Fecha emisión'),
	('COB_DIF_DEVOLUCION_FALTANTE','COB','COBROS','ESP','Dif. Devolución/Faltante'),
	('COB_PAGO_PARCIAL','COB','COBROS','ESP','Pago parcial'),
	('COB_MONTO_PAGAR','COB','COBROS','ESP','Monto a pagar'),
	('COB_NRO_DEPOSITO','COB','COBROS','ESP','Nro. Depósito'),
	('COB_NRO_REFERENCIA','COB','COBROS','ESP','Nro. Referencia'),
	('COB_BANCO_RECEPTOR','COB','COBROS','ESP','Banco Receptor'),
	('COB_MONTO_TOTAL_PAGAR','COB','COBROS','ESP','Monto total a Pagar'),
	('COB_PAGO','COB','COBROS','ESP','Pago'),
	('COB_DIFERENCIA','COB','COBROS','ESP','Diferencia'),
	('COB_DESC','COB','COBROS','ESP','Desc.'),
	('COB_MONTO_DOC','COB','COBROS','ESP','Monto Doc.'),
	('COB_MONTO_PAGO','COB','COBROS','ESP','Monto Pago'),
	('COB_NRO_DOC','COB','COBROS','ESP','Nro. Doc.'),
	('COB_TOTAL_EFECTIVO','COB','COBROS','ESP','Total Efectivo'),
	('COB_TOTAL_CHEQUES','COB','COBROS','ESP','Total Cheques'),
	('COB_TOTAL_DEPOSITOS','COB','COBROS','ESP','Total Depósitos'),
	('COB_TOTAL_TRANSFERENCIAS','COB','COBROS','ESP','Total Transferencias'),
	('COB_TOTAL_OTROS','COB','COBROS','ESP','Total Otros'),
	('COB_TOTAL_GENERAL','COB','COBROS','ESP','Total General'),
	('COB_SELECTOR_METODO_COBRO','COB','COBROS','ESP','Seleccione método de cobro...'),
	('COB_ADD_METODO_PAGO','COB','COBROS','ESP','Agregar método de pago'),
	('COB_METODO_COBRO','COB','COBROS','ESP','Método de cobro'),
	('COB_SELECTOR','COB','COBROS','ESP','Seleccione...'),
	('COB_BOTON_ELIMINAR','COB','COBROS','ESP','Eliminar'),
	('COB_EMPRESA','COB','COBROS','ESP','Empresa'),
	('COB_MONTO_DOCUMENTO','COB','COBROS','ESP','Monto Documento'),
	('COB_HEADER_MESSAGE','COB','COBROS','ESP','Denario Cobros'),
	('COB_EMPTY_TXCONVERSION','COB','COBROS','ESP','La razón de cambio no puede ser vacía'),
	('COB_EMPTY_TXCOMMENT','COB','COBROS','ESP','El comentario no puede ser vacío'),
	('COB_EMPTY_SEPARATE_IGTF_PAY','COB','COBROS','ESP','Pago separado IGTF'),
	('COB_IGTF_LABEL','COB','COBROS','ESP','IGTF'),
	('COB_DAVOUCHER','COB','COBROS','ESP','Fecha Comp Ret'),
	('COB_MSG_AUTOMATED_PREPAID','COB','COBROS','ESP','Anticipo automatico creado con'),
	('COB_LABEL_MONTO','COB','COBROS','ESP','Monto'),
	('COB_LABEL_NRO_RECIBO','COB','COBROS','ESP','Nro. Recibo'),
	('COB_LABEL_ANTICIPO_AUTOMATICO','COB','COBROS','ESP','Este pago creo el anticipo automatico'),
	('COB_MONTO_CONVERSION','COB','COBROS','ESP','Monto Conversión'),
	('COB_ADD_RETENTION','COB','COBROS','ESP','Agregar Retención'),
	('COB_IVA_AMOUNT','COB','COBROS','ESP','Monto IVA'),
	('COB_ISLR_AMOUNT','COB','COBROS','ESP','Monto ISLR'),
	('COB_MONTO_TOTAL_RETENTION','COB','COBROS','ESP','Monto total retenido'),
	('COB_DETAIL_RETENTION','COB','COBROS','ESP','Detalle Retención'),
	('COB_NUMERO_COMPROBANTE','COB','COBROS','ESP','Nro. Comprobante'),
	('COB_IVA_RETENTION','COB','COBROS','ESP','Retención IVA'),
	('COB_ISLR_RETENTION','COB','COBROS','ESP','Retención ISLR'),
	('COB_OTROS_ESPECIFIQUE','COB','COBROS','ESP','Especifique'),
	('COB_MONTO_TOTAL_FINAL','COB','COBROS','ESP','Monto Final'),
	('COB_SAVE_COLLECT_MSG','COB','COBROS','ESP','El Cobro se ha guardado'),
	('COB_SAVE_ANTICIPO_MSG','COB','COBROS','ESP','El Anticipo se ha guardado'),
	('COB_SAVE_RETENTION_MSG','COB','COBROS','ESP','La Retención se ha guardado'),
	('COB_SAVE_IGTF_MSG','COB','COBROS','ESP','El IGTF se ha guardado'),
	('COB_SEND_COLLECT_MSG','COB','COBROS','ESP','El Cobro será enviado'),
	('COB_SEND_ANTICIPO_MSG','COB','COBROS','ESP','El Anticipo será enviado'),
	('COB_SEND_RETENTION_MSG','COB','COBROS','ESP','La Retención será enviado'),
	('COB_SEND_IGTF_MSG','COB','COBROS','ESP','El IGTF será enviado'),
	('COB_OTROS_NOMBRE','COB','COBROS','ESP','Nombre'),
	('COB_AMOUNT_RETENTION_IVA','COB','COBROS','ESP','Monto retenido IVA'),
	('COB_AMOUNT_RETENTION_ISLR','COB','COBROS','ESP','Monto retenido ISLR'),
	('COB_NUMBER_COMPROBANTE_RETENTION','COB','COBROS','ESP','Nro. Comp Ret'),
	('COB_COB_CHANGE_CURRENCY','COB','COBROS','ESP','¿Seguro desea cambiar la moneda? El cobro sera reiniciado!'),
	('COB_ANT_CHANGE_CURRENCY','COB','COBROS','ESP','¿Seguro desea cambiar la moneda? El anticipo sera reiniciado!'),
	('COB_RET_CHANGE_CURRENCY','COB','COBROS','ESP','¿Seguro desea cambiar la moneda? La retención sera reiniciado!'),
	('COB_IGTF_CHANGE_CURRENCY','COB','COBROS','ESP','¿Seguro desea cambiar la moneda? El IGTF sera reiniciado!'),
	('COB_CONFIRM_DELETE', 'COB', 'COBROS', 'ESP', '¿Desea eliminar el Cobro?'),
	('COB_MODULE_COBRO25', 'COB', 'COBROS', 'ESP', 'COBRO 25% IVA'),
	('COB_MSJ_PARTIALPAY_MAYOR_DOCAMOUNT', 'COB', 'COBROS', 'ESP', '¡El pago parcial no puede ser mayor al monto del documento!'),
	('COB_MSJ_PAY_MAYOR_DOCAMOUNT', 'COB', 'COBROS', 'ESP', '¡El pago no puede ser mayor al monto del documento!'),	
	('COB_MSJ_RETENTION_ONLY_TEXT', 'COB', 'COBROS', 'ESP','El comprobante de retenci\u00f3n no debe tener n\u00fameros'),
	('COB_MSJ_RETENTION_ALPHANUMERIC', 'COB', 'COBROS', 'ESP','El comprobante de retenci\u00f3n solo debe tener n\u00fameros y letras'),
	('COB_MSJ_IGTF_MAYOR0', 'COB', 'COBROS', 'ESP','¡Debe seleccionar un IGTF mayor a 0!'),
	('COB_MSJ_HAVE_PAYPARTIAL', 'COB', 'COBROS', 'ESP','Este documento ya tiene pago parcial realizado. ¿Desea verlo?'),
	('COB_MSJ_AMOUNT_MAYOR0', 'COB', 'COBROS', 'ESP','¡El monto a Retener debe ser mayor a 0!'),
	('COB_STATUS_SAVED', 'COB', 'COBROS', 'ESP','Guardado'),
	('COB_STATUS_SAVED', 'COB', 'COBROS', 'ENG','Saved'),
	('COB_STATUS_TO_SEND', 'COB', 'COBROS', 'ESP', 'Por Enviar'),
	('COB_STATUS_SENT', 'COB', 'COBROS', 'ESP', 'Enviado'),
	('COB_TYPE_COBRO', 'COB', 'COBROS', 'ESP', 'Cobro'),
	('COB_TYPE_ANTICIPO', 'COB', 'COBROS', 'ESP', 'Anticipo'),
	('COB_TYPE_RETENCION', 'COB', 'COBROS', 'ESP', 'Retencion'),
	('COB_TYPE_IGTF', 'COB', 'COBROS', 'ESP', 'IGTF'),
	('COB_DEV_STATUS', 'COB', 'COBROS', 'ESP', 'Estatus'),
	('COB_DEV_STATUS', 'COB', 'COBROS', 'ENG', 'Status'),
	('COB_NRO_REF', 'COB', 'COBROS', 'ESP', 'Nro Ref'),
	('COB_NRO_REF', 'COB', 'COBROS', 'ENG', 'Ref No'),
	('COB_FECHA_ANTICIPO', 'COB', 'COBROS', 'ESP', 'Fecha Anticipo'),
	('COB_FECHA_RETENCION', 'COB', 'COBROS', 'ESP', 'Fecha Retención');
		
-- VENDEDORES
DELETE FROM public.application_tags where co_module = 'VND';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES ('VND_VENDEDOR', 'VND', 'VENDEDOR', 'ESP', 'Vendedor'),
	('VND_DIAS_HABILES', 'VND', 'VENDEDOR', 'ESP', 'Días Hábiles'),
	('VND_DIAS_TRANS', 'VND', 'VENDEDOR', 'ESP', 'Días Transcurridos'),
	('VND_DIAS_RESTAN', 'VND', 'VENDEDOR', 'ESP', 'Días Restantes'),
	('VND_CARTERA', 'VND', 'VENDEDOR', 'ESP', 'Cartera Clientes'),
	('VND_CLIENTES_ACTIVOS', 'VND', 'VENDEDOR', 'ESP', 'Clientes Activados'),
	('VND_CLIENTES_NUEVOS', 'VND', 'VENDEDOR', 'ESP', 'Clientes Nuevos'),
	('VND_CLIENTES_NUEVOSACT', 'VND', 'VENDEDOR', 'ESP', 'Clientes Nuevos Activados'),
	('VND_TIPO_PLAN', 'VND', 'VENDEDOR', 'ESP', 'Plan por'),
	('VND_CUOTA_MES', 'VND', 'VENDEDOR', 'ESP', 'Cuota Mes'),
	('VND_VENTA_REAL', 'VND', 'VENDEDOR', 'ESP', 'Venta Real Mes');
	
--TAGS INVENTARIO
DELETE FROM public.application_tags WHERE co_module = 'INV';
--TAGS INVENTARIO
	INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('INV_NOMBRE_MODULO','INV','INVENTARIO','ESP','Inventarios'),
	('INV_NUEVO_INVENTARIO','INV','INVENTARIO','ESP','INVENTARIO'),
	('INV_BUSCAR_INVENTARIO','INV','INVENTARIO','ESP','BUSCAR'),
	('INV_GENERAL_TAB','INV','INVENTARIO','ESP','General'),
	('INV_INVENTARIO_TAB','INV','INVENTARIO','ESP','Inventario'),
	('INV_ACTIVIDADES_TAB','INV','INVENTARIO','ESP','Actividades'),
	('INV_ADJUNTOS_TAB','INV','INVENTARIO','ESP','Adjunto'),
	('INV_COMENTARIO','INV','INVENTARIO','ESP','Comentario'),
	('INV_FECHA','INV','INVENTARIO','ESP','Fecha'),
	('INV_CLIENTSTOCK_TYPES','INV','INVENTARIO','ESP','Tipos de Inventario'),
	('INV_MODAL_SAVE','INV','INVENTARIO','ESP','Guardar'),
	('INV_MODAL_BACK','INV','INVENTARIO','ESP','Atras'),
	('INV_SELECTOR_CLIENTSTOCK','INV','INVENTARIO','ESP','Seleccione tipo de Inventario'),
	('INV_SELECTOR_PLACEHOLDER','INV','INVENTARIO','ESP','Seleccione...'),
	('INV_TYPESTOCK_EXH','INV','INVENTARIO','ESP','Exhibición'),
	('INV_TYPESTOCK_DEP','INV','INVENTARIO','ESP','Depósito'),
	('INV_INGRESE_CANTIDAD','INV','INVENTARIO','ESP','Ingrese Cantidad'),
	('INV_CANTIDAD','INV','INVENTARIO','ESP','Cantidad'),
	('INV_INGRESE_LOTE','INV','INVENTARIO','ESP','Ingrese Lote'),
	('INV_LOTE','INV','INVENTARIO','ESP','Lote'),
	('INV_FECHAVENCIMIENTO','INV','INVENTARIO','ESP','Fecha Vencimiento'),
	('INV_BOTON_ACEPTAR','INV','INVENTARIO','ESP','Aceptar'),
	('INV_BOTON_CANCELAR','INV','INVENTARIO','ESP','Cancelar'),
	('INV_CODIGO','INV','INVENTARIO','ESP','Código'),
	('INV_TOTAL_INVENTARIO','INV','INVENTARIO','ESP','Total Inventario'),
	('INV_UNIDAD','INV','INVENTARIO','ESP','Unidad'),
	('INV_EXH_TYPE','INV','INVENTARIO','ESP','exh'),
	('INV_EXH_NAME','INV','INVENTARIO','ESP','Exhibición'),
	('INV_DEP_TYPE','INV','INVENTARIO','ESP','dep'),
	('INV_DEP_NAME','INV','INVENTARIO','ESP','Depósito'),
	('INV_CLIENTE','INV','INVENTARIO','ESP','Cliente'),
	('INV_STATUS','INV','INVENTARIO','ESP','Estatus'),
	('INV_STATUS_NEW','INV','INVENTARIO','ESP','Nuevo'),
	('INV_STATUS_SEND','INV','INVENTARIO','ESP','Enviado'),
	('INV_STATUS_SAVE','INV','INVENTARIO','ESP','Guardado'),
	('INV_STATUS_TO_SEND','INV','INVENTARIO','ESP','Por Enviar'),
	('INV_NRO_REF','INV','INVENTARIO','ESP','Nro. Ref.'),
	('INV_PED_SUG','INV','INVENTARIO','ESP','Pedido Sugerido'),
	('INV_PREGUNTA_SUGERIR','INV','INVENTARIO','ESP','¿Desea cargar el pedido sugerido?'),
	('INV_HEADER_MESSAGE','INV','INVENTARIO','ESP','Denario Inventario'),
	('INV_ACTIVIDADES_SUBTOTAL','INV','INVENTARIO','ESP','Sub Total.'),
	('INV_ACTIVIDADES_TOTALEXH','INV','INVENTARIO','ESP','Total Exhibición'),
	('INV_ACTIVIDADES_TOTALDEP','INV','INVENTARIO','ESP','Total Depósito'),
	('INV_ACTIVIDADES_NOSTOCKDETAIL','INV','INVENTARIO','ESP','No hay inventario'),
	('INV_MSJ_SAVE_QUESTION_TYPESTOCK','INV','INVENTARIO','ESP','¿Desea guardar el Inventario?'),
	('INV_MSJ_SEND_QUESTION_TYPESTOCK','INV','INVENTARIO','ESP','¿Desea enviar el Inventario?'),
	('INV_ERROR_LIST_ADDRESS','INV','INVENTARIO','ESP','Este cliente no tiene sucursal asignada, por favor consulte su administrador'),
	('INV_MSJ_SAVETYPESTOCK','INV','INVENTARIO','ESP','Inventario guardado con éxito'),
	('INV_MSJ_ERROR_TYPESTOCKS','INV','INVENTARIO','ESP','Debe ingresar alguna cantidad de Inventario o borrar el tipo de Inventario'),
	('INV_DEV_SAVED', 'INV', 'INVENTARIO', 'ESP','Guardado'),
	('INV_DEV_SAVED', 'INV', 'INVENTARIO', 'ENG','Saved'),
	('INV_DEV_TO_BE_SENDED', 'INV', 'INVENTARIO', 'ESP','Por Enviar'),
	('INV_DEV_TO_BE_SENDED', 'INV', 'INVENTARIO', 'ENG','To be sent'),
	('INV_DEV_SENDED', 'INV', 'INVENTARIO', 'ESP','Enviado'),
	('INV_DEV_SENDED', 'INV', 'INVENTARIO', 'ENG','Sent'),
	('INV_DEV_STATUS', 'INV', 'INVENTARIO', 'ESP','Estatus'),
	('INV_ADD_TYPE', 'INV', 'INVENTARIO', 'ESP','Agregar tipo de Inventario'),
	('INV_ADD_TYPE', 'INV', 'INVENTARIO', 'ENG','Add Stock Type'),
	('INV_DEV_STATUS', 'INV', 'INVENTARIO', 'ENG','Status');
	

-- PRODUCTOS
DELETE FROM public.application_tags where co_module = 'PROD';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES ('PROD_NOMBRE_MODULO', 'PROD', 'PRODUCTOS', 'ESP', 'Productos'),
	('PROD_NOMBRE_MODULO', 'PROD', 'PRODUCTOS', 'ENG', 'Products'),
	('PROD_PLACEHOLDER_BUSCAR', 'PROD', 'PRODUCTOS', 'ESP', 'Búsqueda de productos'),
	('PROD_BUSCAR', 'PROD', 'PRODUCTOS', 'ESP', 'Buscar'),
	('PROD_PLACEHOLDER_BUSCAR', 'PROD', 'PRODUCTOS', 'ENG', 'Search products'),
	('PROD_BUSCAR', 'PROD', 'PRODUCTOS', 'ENG', 'Search'),
	('PROD_VER_ESCTRUCTURAS', 'PROD', 'PRODUCTOS', 'ESP', 'Estructuras Productos'),
	('PROD_VER_ESCTRUCTURAS', 'PROD', 'PRODUCTOS', 'ENG', 'Product Structures'),
	('PROD_DETAIL_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Detalle de Producto'),
	('PROD_DETAIL_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Product Detail'),
	('PROD_NAME_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Nombre'),
	('PROD_NAME_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Name'),
	('PROD_COD_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Código'),
	('PROD_COD_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Code'),
	('PROD_STRUCT_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Estructura Producto'),
	('PROD_STRUCT_PROD', 'PROD', 'PRODUCTOS', 'ENG', 'Product Structure'),
	('PROD_DESC_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Descripción'),
	('PROD_DESC_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Description'),
	('PROD_UNIT_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Unidad Venta'),
	('PROD_UNIT_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Sale Unit'),
	('PROD_PRICE_LIST_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Lista Precio'),
	('PROD_PRICE_LIST_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Price List'),
	('PROD_PRICE_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Precio'),
	('PROD_PRICE_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Price'),
	('PROD_CONV_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Tasa Conversión'),
	('PROD_CONV_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Conversion Rate'),
	('PROD_WAREHOUSE_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Almacén'),
	('PROD_WAREHOUSE_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Warehouse'),
	('PROD_STOCK_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Inventario'),
	('PROD_STOCK_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Stock'),
	('PROD_POINTS_PROD', 'PROD', 'PRODUCTOS', 'ESP', 'Puntos'),
	('PROD_POINTS_PROD', 'PROD', 'PRODUCTOS', 'Eng', 'Points'),
	('ADD_PRODUCT', 'PROD', 'DEVOLUCIONES', 'ESP', 'Agregar Producto'),
	('ADD_PRODUCT', 'PROD', 'DEVOLUCIONES', 'ENG', 'Add Product'),
	('PROD_VOLVER', 'PROD', 'PRODUCTOS', 'ESP', 'Volver'),	
	('PROD_VOLVER', 'PROD', 'PRODUCTOS', 'ENG', 'Back');
	
-- DEVOLUCIONES
DELETE FROM public.application_tags where co_module = 'DEV';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES ('DEV_NOMBRE_MODULO', 'DEV', 'DEVOLUCIONES', 'ESP', 'Devoluciones'),
	('DEV_NOMBRE_MODULO', 'DEV', 'DEVOLUCIONES', 'ENG', 'Returns'),
	('DEV_NUEVA_DEVOLUCION', 'DEV', 'DEVOLUCIONES', 'ESP', 'DEVOLUCIÓN'),
	('DEV_NUEVA_DEVOLUCION', 'DEV', 'DEVOLUCIONES', 'ENG', 'New Return'),
	('DEV_BUSCAR_DEVOLUCION', 'DEV', 'DEVOLUCIONES', 'ESP', 'BUSCAR'),
	('DEV_BUSCAR_DEVOLUCION', 'DEV', 'DEVOLUCIONES', 'ENG', 'Find Return'),
	('DEV_PLACEHOLDER_BUSCAR', 'DEV', 'DEVOLUCIONES', 'ESP', 'Búsqueda de devolución'),
	('DEV_BUSCAR', 'DEV', 'DEVOLUCIONES', 'ESP', 'Buscar'),
	('DEV_PLACEHOLDER_BUSCAR', 'DEV', 'DEVOLUCIONES', 'ENG', 'Search returns'),
	('DEV_BUSCAR', 'DEV', 'DEVOLUCIONES', 'ENG', 'Search'),
	('DEV_GENERAL_TAB', 'DEV', 'DEVOLUCIONES', 'ESP', 'General'),
	('DEV_GENERAL_TAB', 'DEV', 'DEVOLUCIONES', 'ENG', 'General'),
	('DEV_PRODUCTOS_TAB', 'DEV', 'DEVOLUCIONES', 'ESP', 'Productos'),
	('DEV_PRODUCTOS_TAB', 'DEV', 'DEVOLUCIONES', 'ENG', 'Products'),
	('DEV_ADJUNTOS_TAB', 'DEV', 'DEVOLUCIONES', 'ESP', 'Adjuntos'),
	('DEV_ADJUNTOS_TAB', 'DEV', 'DEVOLUCIONES', 'ENG', 'Attachments'),
	('DEV_RESPONSABLE_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'Responsable'),
	('DEV_RESPONSABLE_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'Responsible'),
	('DEV_FECHA_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'Fecha'),
	('DEV_FECHA_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'Date'),
	('DEV_PRECINTO_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'No. Precinto'),
	('DEV_PRECINTO_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'No. Seal'),
	('DEV_COMENTARIO_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'Comentario'),
	('DEV_COMENTARIO_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'Comment'),
	('DEV_TIPO_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'Tipo'),
	('DEV_TIPO_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'Type'),
	('DEV_AGREGAR_PRODUCTO', 'DEV', 'DEVOLUCIONES', 'ESP', 'Agregar Producto'),
	('DEV_AGREGAR_PRODUCTO', 'DEV', 'DEVOLUCIONES', 'ENG', 'Add Product'),
	('DEV_VOLVER', 'DEV', 'DEVOLUCIONES', 'ESP', 'Volver'),	
	('DEV_VOLVER', 'DEV', 'DEVOLUCIONES', 'ENG', 'Back'),
	('DEV_LOTE', 'DEV', 'DEVOLUCIONES', 'ESP', 'Lote'),	
	('DEV_LOTE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Batch'),
	('DEV_DOC', 'DEV', 'DEVOLUCIONES', 'ESP', 'Nro Factura'),	
	('DEV_DOC', 'DEV', 'DEVOLUCIONES', 'ENG', 'Document Number'),
	('DEV_FECHA_VENCE', 'DEV', 'DEVOLUCIONES', 'ESP', 'Fecha Venc'),	
	('DEV_FECHA_VENCE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Due Date'),
	('DEV_QU_PRODUCT', 'DEV', 'DEVOLUCIONES', 'ESP', 'Cantidad Devuelta'),	
	('DEV_QU_PRODUCT', 'DEV', 'DEVOLUCIONES', 'ENG', 'Return Quantity'),
	('DEV_UNIT', 'DEV', 'DEVOLUCIONES', 'ESP', 'Unidad'),	
	('DEV_UNIT', 'DEV', 'DEVOLUCIONES', 'ENG', 'Unit'),
	('DEV_MOTIVE', 'DEV', 'DEVOLUCIONES', 'ESP', 'Motivo'),	
	('DEV_MOTIVE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Motive'),
	('DENARIO_DEV', 'DEV', 'DEVOLUCIONES', 'ESP', 'Denario Devolución'),
	('DENARIO_DEV', 'DEV', 'DEVOLUCIONES', 'ENG', 'Denario Return'),
	('DENARIO_DEV_TO_SEND', 'DEV', 'DEVOLUCIONES', 'ESP', '¡Su Devolución será enviada!'),
	('DENARIO_DEV_TO_SEND', 'DEV', 'DEVOLUCIONES', 'ENG', 'Your Return will be send!'),
	('DENARIO_DEV_TO_SEND_OFFLINE', 'DEV', 'DEVOLUCIONES', 'ESP', '¡Su Devolución será enviada al tener conexión de datos!'),
	('DENARIO_DEV_TO_SEND_OFFLINE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Your Return will be send when connection is available!'),
	('DENARIO_DEV_TO_SAVE', 'DEV', 'DEVOLUCIONES', 'ESP', '¡Su Devolución se ha guardado!'),
	('DENARIO_DEV_TO_SAVE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Your Return is saved!'),
	('DENARIO_DEV_CONFIRM_SEND', 'DEV', 'DEVOLUCIONES', 'ESP', '¿Desea enviar la devolución?'),
	('DENARIO_DEV_CONFIRM_SEND', 'DEV', 'DEVOLUCIONES', 'ENG', 'Send this return?'),
	('DENARIO_DEV_NU_REF', 'DEV', 'DEVOLUCIONES', 'ESP', 'Nro. Ref'),
	('DENARIO_DEV_NU_REF', 'DEV', 'DEVOLUCIONES', 'ENG', 'Nu. Ref'),
	('DENARIO_DEV_CLIENT', 'DEV', 'DEVOLUCIONES', 'ESP', 'Cliente'),
	('DENARIO_DEV_CLIENT', 'DEV', 'DEVOLUCIONES', 'ENG', 'Client'),
	('DENARIO_DEV_STATUS', 'DEV', 'DEVOLUCIONES', 'ESP', 'Estatus'),
	('DENARIO_DEV_STATUS', 'DEV', 'DEVOLUCIONES', 'ENG', 'Status'),
	('DENARIO_DEV_DATE', 'DEV', 'DEVOLUCIONES', 'ESP', 'Fecha'),
	('DENARIO_DEV_DATE', 'DEV', 'DEVOLUCIONES', 'ENG', 'Date Return'),
	('MSG_BOTON_SALIR_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','Salir sin guardar'),
	('MSG_BOTON_SALIR_GUARDAR_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','Guardar y salir'),
	('MSG_BOTON_CANCELAR_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','Cancelar'),
	('MSG_BOTON_ACEPTAR_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','Aceptar'),
	('MSG_BOTON_ACEPTAR_DEV', 'DEV', 'DEVOLUCIONES', 'ENG','Ok'),
	('MSG_BOTON_DELETE_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','Eliminar'),
	('MSG_HEADER_ALERTA_DEV', 'DEV', 'DEVOLUCIONES', 'ESP','¡Alerta!'),
	('DENARIO_DEV_SAVED', 'DEV', 'DEVOLUCIONES', 'ESP','Guardado'),
	('DENARIO_DEV_SAVED', 'DEV', 'DEVOLUCIONES', 'ENG','Saved'),
	('DENARIO_DEV_TO_BE_SENDED', 'DEV', 'DEVOLUCIONES', 'ESP','Por Enviar'),
	('DENARIO_DEV_TO_BE_SENDED', 'DEV', 'DEVOLUCIONES', 'ENG','To be sended'),
	('DENARIO_DEV_SENDED', 'DEV', 'DEVOLUCIONES', 'ESP','Enviado'),
	('DENARIO_DEV_SENDED', 'DEV', 'DEVOLUCIONES', 'ENG','Sended'),
	('DENARIO_DEV_CONFIRM_DELETE', 'DEV', 'DEVOLUCIONES', 'ESP', '¿Desea eliminar la devolución?'),
	('DENARIO_DEV_CONFIRM_DELETE', 'DEV', 'DEVOLUCIONES', 'ENG', 'DELETE this return?'),
	('DENARIO_DEV_BOTON_SALIR', 'DEV', 'DEVOLUCIONES', 'ESP','Salir sin guardar'),
	('DENARIO_DEV_BOTON_SALIR', 'DEV', 'DEVOLUCIONES', 'ENG','Exit without saving'),
	('DENARIO_DEV_BOTON_SALIR_GUARDAR', 'DEV', 'DEVOLUCIONES', 'ESP','Guardar y salir'),
	('DENARIO_DEV_BOTON_SALIR_GUARDAR', 'DEV', 'DEVOLUCIONES', 'ENG','Save and exit'),
	('DEV_INVOICE', 'DEV', 'DEVOLUCIONES', 'ESP','Código Factura'),
	('DEV_INVOICE', 'DEV', 'DEVOLUCIONES', 'ENG','Invoice Code'),
	('DEV_INVALID_QU_UNIT', 'DEV', 'DEVOLUCIONES', 'ESP','La cantidad a devolver debe estar entre 1 y'),
	('DEV_INVALID_QU_UNIT', 'DEV', 'DEVOLUCIONES', 'ENG','Return quantity must be between 1 and '),
	('DEV_COD_INVOICE', 'DEV', 'DEVOLUCIONES', 'ESP','Factura'),
	('DEV_COD_INVOICE', 'DEV', 'DEVOLUCIONES', 'ENG','Invoice'),
	('DEV_HEADER_ALERTA', 'DEV', 'DEVOLUCIONES', 'ESP','¡Alerta!'),
	('DEV_RESET_CONFIRMA', 'DEV', 'DEVOLUCIONES', 'ESP','Se ha detectado cambio de la factura por lo que debera iniciar nuevamente la devolución.');
	
	
-- HOME
DELETE FROM public.application_tags where co_module = 'HOME';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('HOME_VISITAS', 'HOME', 'HOME', 'ESP', 'Visitas'),
	('HOME_DESPACHOS', 'HOME', 'HOME', 'ESP', 'Despachos'),
	('HOME_INVENTARIO', 'HOME', 'HOME', 'ESP', 'Inventarios'),
	('HOME_PEDIDOS', 'HOME', 'HOME', 'ESP', 'Pedidos'),
	('HOME_DEVOLUCIONES', 'HOME', 'HOME', 'ESP', 'Devoluciones'),
	('HOME_COBROS', 'HOME', 'HOME', 'ESP', 'Cobros'),
	('HOME_DEPOSITOS', 'HOME', 'HOME', 'ESP', 'Depósitos'),
	('HOME_VENDEDORES', 'HOME', 'HOME', 'ESP', 'Vendedores'),
	('HOME_PRODUCTOS', 'HOME', 'HOME', 'ESP', 'Productos'),
	('HOME_CLIENTES', 'HOME', 'HOME', 'ESP', 'Clientes'),
	('HOME_SINCRONIZAR', 'HOME', 'HOME', 'ESP', 'Sincronizar');
	
		
-- visitas

DELETE FROM public.application_tags where co_module = 'VIS';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('VIS_NOMBRE_MODULO', 'VIS', 'VISITAS', 'ESP','Visitas'),
	('VIS_NOMBRE_MODULO_DESPACHOS', 'VIS', 'VISITAS', 'ESP','Despachos'),
	('VIS_BOTON_LISTA', 'VIS', 'VISITAS', 'ESP','RUTA DE HOY'),
	('VIS_TAB_GENERAL', 'VIS', 'VISITAS', 'ESP','GENERAL'),
	('VIS_TAB_ACTIVIDADES', 'VIS', 'VISITAS', 'ESP','ACTIVIDADES'),
	('VIS_TAB_ADJUNTOS', 'VIS', 'VISITAS', 'ESP','ADJUNTOS'),
	('VIS_CLIENTE', 'VIS', 'VISITAS', 'ESP','Cliente: '),
	('VIS_REF', 'VIS', 'VISITAS', 'ESP','Nro Ref.: '),
	('VIS_STATUS', 'VIS', 'VISITAS', 'ESP','Estatus: '),
	('VIS_FECHA', 'VIS', 'VISITAS', 'ESP','Fecha: '),
	('VIS_EMPRESA', 'VIS', 'VISITAS', 'ESP','Empresa: '),
	('VIS_BOTON_EVENTOS', 'VIS', 'VISITAS', 'ESP','AÑADIR ACTIVIDAD/EVENTO'),
	('VIS_EVENTO', 'VIS', 'VISITAS', 'ESP','Evento'),
	('VIS_BOTON_INICIAR', 'VIS', 'VISITAS', 'ESP','INICIAR VISITA'),
	('VIS_BOTON_INICIAR_DESPACHO', 'VIS', 'VISITAS', 'ESP','INICIAR DESPACHO'),
	('VIS_ACTIVIDAD', 'VIS', 'VISITAS', 'ESP','Actividad'),
	('VIS_OBSERVACION', 'VIS', 'VISITAS', 'ESP','Observación'),
	('VIS_MOTIVO', 'VIS', 'VISITAS', 'ESP','Motivo'),
	('VIS_COMENTARIO', 'VIS', 'VISITAS', 'ESP','Comentario'),
	('VIS_OPERACION', 'VIS', 'VISITAS', 'ESP','Operación'),
	('VIS_SUCURSAL', 'VIS', 'VISITAS', 'ESP', 'Sucursal'),	
	('VIS_HEADER_MENSAJE', 'VIS', 'VISITAS', 'ESP', 'Denario - Visita'),
	('VIS_MENSAJE_SELEC_CLIENTE', 'VIS', 'VISITAS', 'ESP', 'Seleccione un Cliente'),
	('VIS_MENSAJE_ENVIAR', 'VIS', 'VISITAS', 'ESP', '¿Desea enviar la visita?'),
	('VIS_MENSAJE_ENVIAR_DESPACHO', 'VIS', 'VISITAS', 'ESP', '¿Desea enviar el despacho?'),
	('VIS_MENSAJE_AGREGUE_ACT', 'VIS', 'VISITAS', 'ESP', 'Debe agregar al menos una actividad para poder enviar la visita'),
	('VIS_MENSAJE_VISITA_GUARDA', 'VIS', 'VISITAS', 'ESP', 'La visita se ha guardado'),
	('VIS_INIT_WARN', 'VIS', 'VISITAS', 'ESP','Debe iniciar la visita para continuar'),
	('VIS_FECHA_VISITA', 'VIS', 'VISITAS', 'ESP','Fecha de la Visita:'),
	('VIS_FECHA_VISITA_DESPACHO', 'VIS', 'VISITAS', 'ESP','Fecha del Despacho'),
	('VIS_BORRAR_EXITO', 'VIS', 'VISITAS', 'ESP','Se eliminó la visita de manera exitosa'),
	('VIS_BORRAR_CONFIRMA', 'VIS', 'VISITAS', 'ESP','¿Desea borrar la visita? Esta acción no se puede deshacer.'),
	('VIS_RESET_CONFIRMA', 'VIS', 'VISITAS', 'ESP','Se ha detectado cambio del cliente por lo que debera iniciar nuevamente el pedido.'),
	('VIS_MENSAJE_COORDENADAS', 'VIS', 'VISITAS', 'ESP','Esta sucursal no tiene coordenadas asignadas. ¿Desea agregarlas?'),
	('VIS_MENSAJE_CLIENT_SUCURSAL', 'VIS', 'VISITAS', 'ESP','Ya existe un despacho para este cliente en esta sucursal.'),
	('VIS_SEE_ROUTE', 'VIS', 'VISITAS', 'ESP','Ver ruta'),
	('VIS_MENSAJE_NO_COORDENADAS_DESTINO', 'VIS', 'VISITAS', 'ESP','Faltan coordenadas destino(Cliente)'),
	('VIS_MENSAJE_NO_COORDENADAS_ORIGEN', 'VIS', 'VISITAS', 'ESP','Faltan coordenadas origen (Transportista)'),
	('VIS_SELECT_STATUS_DESPACHO', 'VIS', 'VISITAS', 'ESP','Seleccione estado de despacho'),
	('VIS_STATUS_DESPACHO', 'VIS', 'VISITAS', 'ESP','Estado de despacho'),
	('VIS_DESPACHADO', 'VIS', 'VISITAS', 'ESP','Despachado'),
	('VIS_NO_DESPACHADO', 'VIS', 'VISITAS', 'ESP','No despachado'),
	('VIS_CAMPO_OBLIGATORIO', 'VIS', 'VISITAS', 'ESP','Campo Obligatorio'),
	('VIS_MENSAJE_DESPACHO', 'VIS', 'VISITAS', 'ESP','Debe llenar el campo observación'),
	('VIS_BOTON_NUEVA', 'VIS', 'VISITAS', 'ESP','NUEVA VISITA'),
	('VIS_BOTON_NUEVA_DESPACHO', 'VIS', 'VISITAS', 'ESP','Nuevo Despacho'),
	('VIS_GUIAS_DESPACHO', 'VIS', 'VISITAS', 'ESP','Guías de Despacho'),
	('VIS_NO_GUIAS_DESPACHO', 'VIS', 'VISITAS', 'ESP','No hay guías de despacho disponibles');


-- TAGS DEPOSITOS
DELETE FROM public.application_tags WHERE co_module = 'DEP';
-- TAGS DEPOSITOS
INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('DEP_NOMBRE_MODULO','DEP','DEPOSITOS','ESP','Depósitos'),
	('DEP_MODULE_NUEVO_DEPOSITO','DEP','DEPOSITOS','ESP','DEPÓSITO'),
	('DEP_MODULE_BUSCAR','DEP','DEPOSITOS','ESP','BUSCAR'),
	('DEP_PESTANA_GENERAL','DEP','DEPOSITOS','ESP','General'),
	('DEP_PESTANA_COBROS','DEP','DEPOSITOS','ESP','Cobros'),
	('DEP_PESTANA_TOTAL','DEP','DEPOSITOS','ESP','Total'),
	('DEP_EMPRESA','DEP','DEPOSITOS','ESP','Empresa'),
	('DEP_FECHA_DEP','DEP','DEPOSITOS','ESP','Fecha Depósito'),
	('DEP_MONEDA','DEP','DEPOSITOS','ESP','Moneda'),
	('DEP_BANCO','DEP','DEPOSITOS','ESP','Banco'),
	('DEP_COMENTARIO','DEP','DEPOSITOS','ESP','Comentario'),
	('DEP_NRO_PLANTILLA','DEP','DEPOSITOS','ESP','Nro. Plantilla'),
	('DEP_PLACEHOLDER_LISTBANK','DEP','DEPOSITOS','ESP','Seleccione Banco...'),
	('DEP_FECHA_DOC','DEP','DEPOSITOS','ESP','Fecha Doc'),
	('DEP_SELECT_COB_DEP','DEP','DEPOSITOS','ESP','Seleccione los Cobros a depositar'),
	('DEP_COB_DEP','DEP','DEPOSITOS','ESP','Cobros a depositar'),
	('DEP_SELECCIONE','DEP','DEPOSITOS','ESP','Selec'),
	('DEP_CLIENTE','DEP','DEPOSITOS','ESP','Cliente'),
	('DEP_FECHA_COB','DEP','DEPOSITOS','ESP','Fecha Cob.'),
	('DEP_CODIGO_COB','DEP','DEPOSITOS','ESP','Cod. Cobro'),
	('DEP_MONTO_DEPOSITO','DEP','DEPOSITOS','ESP','Monto Depósito'),
	('DEP_MONTO_COBRO','DEP','DEPOSITOS','ESP','Monto Cobro'),
	('DEP_MONTO_TOTAL_DEP','DEP','DEPOSITOS','ESP','Monto total depositado'),
	('DEP_HEADER_MESSAGE','DEP','DEPOSITOS','ESP','Denario Depósito'),
	('DEP_SAVE_MSG','DEP','DEPOSITOS','ESP','El Depósito se ha guardado'),
	('DEP_SEND_MSG','DEP','DEPOSITOS','ESP','El Depósito será enviado'),
	('DEP_DEV_STATUS', 'DEP', 'DEPOSITOS', 'ESP', 'Estatus'),
	('DEP_DEV_STATUS', 'DEP', 'DEPOSITOS', 'ENG', 'Status'),
	('DEP_DEV_DATE', 'DEP', 'DEPOSITOS', 'ESP', 'Fecha'),
	('DEP_DEV_DATE', 'DEP', 'DEPOSITOS', 'ENG', 'Date Return'),
	('DEP_DEV_SAVED', 'DEP', 'DEPOSITOS', 'ESP','Guardado');

	
--	MENSAJES
DELETE FROM public.application_tags where co_module = 'MSG';

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 	
	('MSG_BOTON_SALIR', 'MSG', 'MENSAJES', 'ESP','Salir sin guardar'),
	('MSG_BOTON_SALIR_GUARDAR', 'MSG', 'MENSAJES', 'ESP','Guardar y salir'),
	('MSG_BOTON_CANCELAR', 'MSG', 'MENSAJES', 'ESP','Cancelar'),
	('MSG_HEADER_ALERTA', 'MSG', 'MENSAJES', 'ESP','¡Alerta!');
	
--	ADJUNTOS
DELETE FROM public.application_tags where co_module = 'ADJ';	

INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('ADJ_BUSCAR_FOTO', 'ADJ', 'ADJUNTOS', 'ESP','BUSCAR FOTO'),
	('ADJ_TOMAR_FOTO', 'ADJ', 'ADJUNTOS', 'ESP','TOMAR FOTO'),
	('ADJ_BUSCAR_FOTO', 'ADJ', 'ADJUNTOS', 'ENG','SEARCH PHOTO'),
	('ADJ_TOMAR_FOTO', 'ADJ', 'ADJUNTOS', 'ENG','TAKE PHOTO'),
	('ADJ_MSJ_LIMITE', 'ADJ', 'ADJUNTOS', 'ESP','Numero de imagenes permitidas: '),
	('ADJ_TITULO_PICKER', 'ADJ', 'ADJUNTOS', 'ESP','Seleccione una o más imagenes'),
	('ADJ_TITULO_ALBUM', 'ADJ', 'ADJUNTOS', 'ESP','Elija un álbum'),
	('ADJ_TITULO_LIBRERIA', 'ADJ', 'ADJUNTOS', 'ESP','Click aqui para cambiar librería'),
	('ADJ_ACORDEON_IMAGENES', 'ADJ', 'ADJUNTOS', 'ESP','Imagenes'),
	('ADJ_ACORDEON_FIRMA', 'ADJ', 'ADJUNTOS', 'ESP','Firma'),
	('ADJ_ACORDEON_ARCHIVO', 'ADJ', 'ADJUNTOS', 'ESP','Archivo'),
	('ADJ_SUBIR_ARCHIVO', 'ADJ', 'ADJUNTOS', 'ESP','Subir Archivo');

--	COMUNES
DELETE FROM public.application_tags WHERE co_module = 'DEN';
INSERT INTO public.application_tags(
	co_application_tag, co_module, na_module, co_language, tag)
	VALUES 
	('DENARIO_NOMBRE_APP','DEN','DENARIO','ESP','Denario Premium'),
	('DENARIO_BOTON_SALIR_GUARDAR','DEN','DENARIO','ESP','Guardar y salir'),
	('DENARIO_BOTON_SALIR','DEN','DENARIO','ESP','Salir sin guardar'),
	('DENARIO_BOTON_CANCELAR','DEN','DENARIO','ESP','Cancelar'),
	('DENARIO_SCROLL_TEXT','DEN','DENARIO','ESP','Por Favor Espere...'),
	('DENARIO_BOTON_ACEPTAR','DEN','DENARIO','ESP','Aceptar'),
	('DENARIO_BOTON_AGREGAR','DEN','DENARIO','ESP','Agregar'),
	('DENARIO_BOTON_BORRAR','DEN','DENARIO','ESP','Borrar'),
	('DENARIO_BOTON_OK','DEN','DENARIO','ESP','Ok'),
	('DENARIO_BOTON_GUARDAR','DEN','DENARIO','ESP','Guardar'),
	('DENARIO_HEADER_ALERTA', 'DEN', 'DENARIO', 'ESP','¡Alerta!'),	
	('DENARIO_CAMPO_OBLIGATORIO', 'DEN', 'DENARIO', 'ESP','¡Campo Obligatorio!'),
	('DENARIO_CAMBIO_DIRECCION', 'DEN', 'DENARIO', 'ESP','¿Seguro desea cambiar la sucursal del cliente?'),
	('DENARIO_MSG_GPS', 'DEN', 'DENARIO', 'ESP', 'Para poder grabar la ubicación, te recomendamos activar el servicio de localización en tu dispositivo'),
	('DENARIO_ERR_GPS', 'DEN', 'DENARIO', 'ESP', 'Falló la ubicación. Revise GPS.'),
	('DENARIO_SELEC_FECHA', 'DEN', 'DENARIO', 'ESP', 'Seleccione una fecha'),
	('DENARIO_ERROR_SYNCRO', 'DEN', 'DENARIO', 'ESP', 'No hay conexión a internet, no se puede sincronizar');