export class Client {
    static clientJson(obj: Client) {
        return new Client(
            obj['idClient'],
            obj['coClient'],
            obj['lbClient'],
            obj['naClient'],
            obj['nuRif'],
            obj['idChannel'],
            obj['idWarehouse'],
            obj['idHeadQuarter'],
            obj['idList'],
            obj['idPaymentCondition'],
            obj['coPaymentCondition'],
            obj['naPaymentCondition'],
            obj['inSuspension'],
            obj['quDiscount'],
            obj['naEmail'],
            obj['nuCreditLimit'],
            obj['naWebSite'],
            obj['idCurrency'],
            obj['coCurrency'],
            obj['multimoneda'],
            obj['coEnterprise'],
            obj['idEnterprise'],
            obj['channel'],
            obj['lblEnterprise'],
            obj['naPriceList'],
            obj['naResponsible'],
            obj['nuPhone'],
            obj['saldo1'],
            obj['saldo1Conver'],
            obj['saldo2'],
            obj['saldo2Conver'],
            obj['txAddress'],
            obj['coordenada'],
            obj['editable'],
            obj['idAddressClients'],
            obj['coAddressClients'],
            obj['collectionIva'],
        );
    }

    constructor(
        public idClient: number,
        public coClient: string,
        public lbClient: string,
        public naClient: string,
        public nuRif: string,
        public idChannel: number,
        public idWarehouse: number,
        public idHeadQuarter: number,
        public idList: number,
        public idPaymentCondition: number,
        public coPaymentCondition: string,
        public naPaymentCondition: string,
        public inSuspension: boolean,
        public quDiscount: number,
        public naEmail: string,
        public nuCreditLimit: number,
        public naWebSite: string,
        public idCurrency: number,
        public coCurrency: string,
        public multimoneda: string,
        public coEnterprise: string,
        public idEnterprise: number,
        public channel: string,
        public lblEnterprise: string,
        public naPriceList: string,
        public naResponsible: string,
        public nuPhone: string,
        public saldo1: number,
        public saldo1Conver: number,
        public saldo2: number,
        public saldo2Conver: number,
        public txAddress: string,
        public coordenada: string,
        public editable: string,
        public idAddressClients: number,
        public coAddressClients: string,
        public collectionIva: boolean,
    ) { }

}