export class ClientStockSuggestedOrder {
  static fromJson(obj: ClientStockSuggestedOrder): ClientStockSuggestedOrder {
    return new ClientStockSuggestedOrder(
      obj['idClientStockSuggestedOrder'] ?? null,
      obj['coClientStockSuggestedOrder'],
      obj['coClientStock'],
      obj['idClientStock'] ?? null,
      obj['idClient'],
      obj['coClient'],
      obj['idAddressClient'],
      obj['coAddressClient'],
      obj['idEnterprise'],
      obj['coEnterprise'],
      obj['idUser'],
      obj['coUser'],
      obj['daysSinceLast'] ?? 1,
      obj['daysUntilNext'] ?? 1,
      obj['byDispatchAndReturn'] ?? 0,
      obj['idCurrency'] ?? null,
      obj['coCurrency'] ?? null,
      obj['daSuggested'] ?? '',
      obj['nuDetails'] ?? 0,
      obj['coOrder'] ?? null,
      obj['idOrder'] ?? null,
      obj['inOrderSent'] ?? 0,
      obj['details'] ?? [],
    );
  }

  constructor(
    public idClientStockSuggestedOrder: number | null = null,
    public coClientStockSuggestedOrder: string = '',
    public coClientStock: string = '',
    public idClientStock: number | null = null,
    public idClient: number = 0,
    public coClient: string = '',
    public idAddressClient: number = 0,
    public coAddressClient: string = '',
    public idEnterprise: number = 0,
    public coEnterprise: string = '',
    public idUser: number = 0,
    public coUser: string = '',
    public daysSinceLast: number = 1,
    public daysUntilNext: number = 1,
    public byDispatchAndReturn: number = 0,
    public idCurrency: number | null = null,
    public coCurrency: string | null = null,
    public daSuggested: string = '',
    public nuDetails: number = 0,
    public coOrder: string | null = null,
    public idOrder: number | null = null,
    public inOrderSent: number = 0,
    public details: ClientStockSuggestedOrderDetail[] = [],
  ) { }
}

export class ClientStockSuggestedOrderDetail {
  static fromJson(obj: ClientStockSuggestedOrderDetail): ClientStockSuggestedOrderDetail {
    return new ClientStockSuggestedOrderDetail(
      obj['idClientStockSuggestedOrderDetail'] ?? null,
      obj['coClientStockSuggestedOrderDetail'],
      obj['coClientStockSuggestedOrder'],
      obj['idProduct'],
      obj['coProduct'] ?? '',
      obj['naProduct'] ?? '',
      obj['idProductUnit'],
      obj['coProductUnit'] ?? '',
      obj['idUnit'] ?? 0,
      obj['coUnit'] ?? '',
      obj['naUnit'] ?? '',
      obj['idEnterprise'] ?? 0,
      obj['coEnterprise'] ?? '',
      obj['posicion'] ?? 0,
      obj['quUnitSuggested'] ?? 0,
      obj['previousStock'] ?? 0,
      obj['currentStock'] ?? 0,
      obj['dispatchedStock'] ?? 0,
      obj['straightSwapStock'] ?? 0,
      obj['returnedStock'] ?? 0,
      obj['initialStock'] ?? 0,
      obj['soldUnits'] ?? 0,
      obj['estimatedDailyUnits'] ?? 0,
    );
  }

  constructor(
    public idClientStockSuggestedOrderDetail: number | null = null,
    public coClientStockSuggestedOrderDetail: string = '',
    public coClientStockSuggestedOrder: string = '',
    public idProduct: number = 0,
    public coProduct: string = '',
    public naProduct: string = '',
    public idProductUnit: number = 0,
    public coProductUnit: string = '',
    public idUnit: number = 0,
    public coUnit: string = '',
    public naUnit: string = '',
    public idEnterprise: number = 0,
    public coEnterprise: string = '',
    public posicion: number = 0,
    public quUnitSuggested: number = 0,
    public previousStock: number = 0,
    public currentStock: number = 0,
    public dispatchedStock: number = 0,
    public straightSwapStock: number = 0,
    public returnedStock: number = 0,
    public initialStock: number = 0,
    public soldUnits: number = 0,
    public estimatedDailyUnits: number = 0,
  ) { }
}
