export class DocumentSale {

  static documentSaleJson(obj: DocumentSale) {
    return new DocumentSale(
      obj['idDocument'],
      obj['idClient'],
      obj['coClient'],
      obj['idDocumentSaleType'],
      obj['coDocumentSaleType'],
      obj['daDocument'],
      obj['daDueDate'],
      obj['nuAmountBase'],
      obj['nuAmountDiscount'],
      obj['nuAmountTax'],
      obj['nuAmountTotal'],
      obj['nuAmountPaid'],
      obj['nuBalance'],
      obj['coCurrency'],
      obj['idCurrency'],
      obj['nuDocument'],
      obj['txComment'],
      obj['coDocument'],
      obj['coCollection'],
      obj['nuValueLocal'],
      obj['stDocumentSale'],
      obj['coEnterprise'],
      obj['idEnterprise'],
      obj['naType'],
      obj['isSelected'],
      obj['positionCollecDetails'],
      obj['nuAmountRetention'],
      obj['nuAmountRetention2'],
      obj['daVoucher'],
      obj['nuVaucherRetention'],
      obj['igtfAmount'],
      obj['txConversion'],
      obj['inPaymentPartial'],
      obj['historicPaymentPartial'],
      obj['isSave'],
      obj['colorRow'],
      obj['daUpdate'],
      obj['missingRetention'],
    );
  }

  constructor(
    public idDocument: number = 0,
    public idClient: number = 0,
    public coClient: string = "",
    public idDocumentSaleType: number = 0,
    public coDocumentSaleType: string = "",
    public daDocument: string = "",
    public daDueDate: string = "",
    public nuAmountBase: number = 0,
    public nuAmountDiscount: number = 0,
    public nuAmountTax: number = 0,
    public nuAmountTotal: number = 0,
    public nuAmountPaid: number = 0,
    public nuBalance: number = 0,
    public coCurrency: string = "",
    public idCurrency: number = 0,
    public nuDocument: string = "",
    public txComment: string = "",
    public coDocument: string = "",
    public coCollection: string = "",
    public nuValueLocal: number = 0,
    public stDocumentSale: number = 0,
    public coEnterprise: string = "",
    public idEnterprise: number = 0,
    public naType: string = "",
    public isSelected: boolean = false,
    public positionCollecDetails: number = 0,
    public nuAmountRetention: number = 0,
    public nuAmountRetention2: number = 0,
    public daVoucher: string = "",
    public nuVaucherRetention: string = "",
    public igtfAmount = 0,
    public txConversion = 0,
    public inPaymentPartial: boolean = false,
    public historicPaymentPartial: boolean = false,
    public isSave: boolean = false,
    public colorRow: string = "",
    public daUpdate: string = "",
    public missingRetention: boolean = false,
  ) { }
}
