import { OrderDetail } from "./orderDetail";

export class Orders {

    static ordersJson(obj: Orders) {
        return new Orders(
            obj['idOrder'],
            obj['coOrder'],
            obj['coClient'],
            obj['idClient'],
            obj['daOrder'],
            obj['daCreated'],
            obj['naResponsible'],
            obj['idUser'],
            obj['idOrderCreator'],
            obj['inOrderReview'],
            obj['nuAmountTotal'],
            obj['nuAmountFinal'],
            obj['coCurrency'],
            obj['daDispatch'],
            obj['txComment'],
            obj['nuPurchase'],
            obj['coEnterprise'],
            obj['coUser'],
            obj['coPaymentCondition'],
            obj['idPaymentCondition'],
            obj['idEnterprise'],
            obj['coAddress'],
            obj['idAddress'],
            obj['nuAmountDiscount'],
            obj['nuAmountTotalBase'],
            obj['stOrder'],
            obj['coordenada'],
            obj['nuDiscount'],
            obj['idCurrency'],
            obj['idCurrencyConversion'],
            obj['nuValueLocal'],
            obj['nuAmountTotalConversion'],
            obj['nuAmountFinalConversion'],
            obj['procedencia'],
            obj['nuAmountTotalBaseConversion'],
            obj['nuAmountDiscountConversion'],
            obj['idOrderType'],
            obj['orderDetails'],
            obj['nuDetails'],
            obj['nuAmountTotalProductDiscount'],
            obj['nuAmountTotalProductDiscountConversion'], 
            obj['hasAttachments'],
            obj['nuAttachments'],
            obj['idDistributionChannel'] || null,
            obj['coDistributionChannel'] || null         
        );
    }
  
    constructor(
        public idOrder: number | null,
        public coOrder: string,
        public coClient: string,
        public idClient: number,
        public daOrder: string,
        public daCreated: string,
        public naResponsible: string,
        public idUser: number,
        public idOrderCreator: number,
        public inOrderReview: boolean,
        public nuAmountTotal: number,
        public nuAmountFinal: number,
        public coCurrency: string,
        public daDispatch: string | null,
        public txComment: string,
        public nuPurchase: string,
        public coEnterprise: string,
        public coUser: string, 
        public coPaymentCondition: string,
        public idPaymentCondition: number,
        public idEnterprise: number,
        public coAddress: string,
        public idAddress: number,
        public nuAmountDiscount: number,
        public nuAmountTotalBase: number,
        public stOrder: number,
        public coordenada: string,
        public nuDiscount: number,
        public idCurrency: number,
        public idCurrencyConversion: number,
        public nuValueLocal: number,
        public nuAmountTotalConversion: number,
        public nuAmountFinalConversion: number,
        public procedencia: string,
        public nuAmountTotalBaseConversion: number,
        public nuAmountDiscountConversion: number,
        public idOrderType: number,
        public orderDetails: OrderDetail[],
        public nuDetails: number,
        public nuAmountTotalProductDiscount: number,
        public nuAmountTotalProductDiscountConversion: number,
        public hasAttachments: boolean,
        public nuAttachments: number,
        public idDistributionChannel: number | null = null,
        public coDistributionChannel: string | null = null,        
        
    ) { }
  }