export interface TablesLastUpdate {
  [key: string]: any;
  addressClientTableLastUpdate: string,
  bankTableLastUpdate: string,
  clientTableLastUpdate: string,
  distributionChannelTableLastUpdate: string,
  documentSaleTableLastUpdate: string,
  documentSaleTypeTableLastUpdate: string,
  enterpriseTableLastUpdate: string,
  incidenceMotiveTableLastUpdate: string,
  incidenceTypeTableLastUpdate: string,
  priceListTableLastUpdate: string,
  productTableLastUpdate: string,
  returnMotiveTableLastUpdate: string,
  returnTypeTableLastUpdate: string,
  bankAccountTableLastUpdate: string,
  listTableLastUpdate: string,
  stockTableLastUpdate: string,
  discountTableLastUpdate: string,
  paymentConditionTableLastUpdate: string,
  productUnitTableLastUpdate: string,
  visitTableLastUpdate: string,
  ivaListTableLastUpdate: string,
  warehouseTableLastUpdate: string,
  globalDiscountTableLastUpdate: string,
  clientBankAccountTableLastUpdate: string,
  productMinMulFavTableLastUpdate: string,
  userInformationTableLastUpdate: string,
  currencyEnterpriseTableLastUpdate: string,
  currencyRelationTableLastUpdate: string,
  conversionTypeTableLastUpdate: string,
  typeProductStructureTableLastUpdate: string,
  productStructureTableLastUpdate: string,
  productStructureCountTableLastUpdate: string,
  unitTableLastUpdate: string,
  orderTypeTableLastUpdate: string,
  userProductFavTableLastUpdate: string,
  clientAvgProductTableLastUpdate: string,
  igtfListTableLastUpdate: string,
  invoiceTableLastUpdate: string,
  invoiceDetailTableLastUpdate: string,
  invoiceDetailUnitTableLastUpdate: string,
  clientChannelOrderTypeTableLastUpdate: string,
  orderTypeProductStructureTableLastUpdate: string,
  orderTableLastUpdate: string,
  transactionStatusTableLastUpdate: string,
  transactionTypeTableLastUpdate: string,
  statusTableLastUpdate: string,
  collectionTableLastUpdate: string,
  returnTableLastUpdate:string,
  clientStockTableLastUpdate:string,
  depositTableLastUpdate:string,
  orderDetailTableLastUpdate:string,
  orderDetailUnitTableLastUpdate:string,
  orderDetailDiscountTableLastUpdate:string,
  page: number

}
